# Generated by Django 2.1.5 on 2019-04-11 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
